APT::FTPArchive::Release {
  Origin "SentinelOS";
  Label "SentinelOS";
  Suite "stable";
  Codename "ambroso";
  Architectures "amd64";
  Components "main";
  Description "SentinelOS public package repository";
};
